### ISSUE TITLE
ドメイン違い（開発環境）のテストについて

### ISSUE THREAD

**Issue by w-noriko** [lifull-dev/bucky-core#72]
stg環境およびdev環境でのテストを実行したいのですが、ソース上のURL記載の部分をホスト名以降のディレクトリのみの記載で、実行コマンドでホスト名を指定するようなことはできないでしょうか。
よろしくお願い致します。

**Comment by hikimochi** [comment]
yamlはerbが使えるようになっていますので、
以下のようにテストコードを実装して頂ければと思います。
例として以下のようなコードになります。

```
cases:
  - case_name: example_1
    func: トップページを開く
    desc: トップページを開き、タイトルが一致していること
    procs:
      - proc: トップページを開く
        exec:
          operate: go
          url: <%= ENV['BUCKY_FQDN'] %>/top/
```

実行コマンドの例

```
BUCKY_FQDN=https://www.test-env.com bucky run -D pc -c example_1
BUCKY_FQDN=https://www.stg-env.com bucky run -D pc -c example_1
BUCKY_FQDN=https://www.live-env.com bucky run -D pc -c example_1
```

環境変数に入れておくのも楽かと思います！
